version: "3"

services:
  api:
    build: 
        context: .
        dockerfile: api.Dockerfile
    container_name: LetsTalkAPI
    volumes:
        - api:/usr/src/app/

  ui:
    build: 
        context: .
        dockerfile: ui.Dockerfile
    container_name: LetsTalkUI
    volumes:
        - ui:/usr/src/ui/
    ports:
        - "8081:8081"

volumes:
    api:
    ui: